version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: unit tests
          command: docker run -w $PWD -v $PWD:$PWD --entrypoint sh sparkprime/jsonnet tests.sh
      - run:
          name: docs
          command: docker run --rm -u $UID -it -p 8000:8000 -v $PWD:/docs squidfunk/mkdocs-material build
